on:
  push:
    branches:
      - main # Adjust the branch name as needed
name: pre-prod-deployment
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Asanka motors Deployment
      run: |
        # Replace the following with your actual deployment commands
        echo "Deploying to pre-production"
        
        # Example: If 'deployepreprod' is the correct command
        # deploy
        
        # Example: If 'taproDev/asankamotors deploy' is the correct command
        # taproDev/asankamotors deploy --server ${{ secrets.FTP_SERVER }} --username ${{ secrets.FTP_USERNAME }} --password ${{ secrets.FTP_PASSWORD }}
